apiVersion: skaffold/v1
kind: Config
metadata:
  name: apply-labels
deploy:
  kubectl:
    manifests:
    - k8s/applylabels.yml
build:
  tagPolicy:
    gitCommit: {}
  artifacts:
  - image: discoenv/apply-labels
  local: {}